category:
  fields:
    - name: 'author'
      type: 'str'
      tags:
        - label: 'contributor'
          refinement: 'contributor'
        - label: 'creator'
          refinement: 'creator'
        - label: 'artist'
          refinement: 'contributor'
    - name: 'description'
      type: 'str'
      tags:
        - label: 'description'
        - label: 'notes'
    - name: 'filename'
      type: 'str'
      tags:
        - label: 'filenames'
        - label: 'file names'
        - label: 'file name'
        - label: 'filename'
        - label: 'media'
    - name: 'category'
      type: 'str'
      tags:
        - label: 'genre'
    - name: 'title'
      type: 'str'
      tags:
        - label: 'title'